In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

print("TensorFlow:", tf.__version__)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)

print("Everything is working successfully!")

TensorFlow: 2.21.0
Pandas: 3.0.5
NumPy: 2.4.6
Scikit-learn: 1.9.0
Everything is working successfully!

In [3]:
import sys
print(sys.executable)

d:\DL Project\Heart_Disease_Prediction\.venv\Scripts\python.exe

In [4]:
# Objective : Load and Understand the Dataset
import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

# Display numbers with 2 decimal places
pd.set_option("display.float_format", "{:.2f}".format)

In [5]:
# Load dataset
df = pd.read_csv("../data/raw_data/cardio_train.csv", sep=";")

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [6]:
df.head(10)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.00,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.00,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.00,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.00,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.00,100,60,1,1,0,0,0,0
5,8,21914,1,151,67.00,120,80,2,2,0,0,0,0
6,9,22113,1,157,93.00,130,80,3,1,0,0,1,0
7,12,22584,2,178,95.00,130,90,3,3,0,0,1,1
8,13,17668,1,158,71.00,110,70,1,1,0,0,1,0
9,14,19834,1,164,68.00,110,60,1,1,0,0,0,0

In [7]:
df.tail(10)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
69990,99986,15094,1,168,72.00,110,70,1,1,0,0,1,1
69991,99988,20609,1,159,72.00,130,90,2,2,0,0,1,0
69992,99990,18792,1,161,56.00,170,90,1,1,0,0,1,1
69993,99991,19699,1,172,70.00,130,90,1,1,0,0,1,1
69994,99992,21074,1,165,80.00,150,80,1,1,0,0,1,1
69995,99993,19240,2,168,76.00,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.00,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.00,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.00,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.00,120,80,2,1,0,0,1,0

In [8]:
rows, columns = df.shape

print("Number of Rows :", rows)
print("Number of Columns :", columns)

Number of Rows : 70000
Number of Columns : 13

In [9]:
print("Columns in Dataset:\n")

for column in df.columns:
    print(column)

Columns in Dataset:

id
age
gender
height
weight
ap_hi
ap_lo
cholesterol
gluc
smoke
alco
active
cardio

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [11]:
df.dtypes

id               int64
age              int64
gender           int64
height           int64
weight         float64
ap_hi            int64
ap_lo            int64
cholesterol      int64
gluc             int64
smoke            int64
alco             int64
active           int64
cardio           int64
dtype: object

In [12]:
df.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.00,70000.00,70000.00,70000.00,70000.00,70000.00,70000.00,70000.00,70000.00,70000.00,70000.00,70000.00,70000.00
mean,49972.42,19468.87,1.35,164.36,74.21,128.82,96.63,1.37,1.23,0.09,0.05,0.80,0.50
std,28851.30,2467.25,0.48,8.21,14.40,154.01,188.47,0.68,0.57,0.28,0.23,0.40,0.50
min,0.00,10798.00,1.00,55.00,10.00,-150.00,-70.00,1.00,1.00,0.00,0.00,0.00,0.00
25%,25006.75,17664.00,1.00,159.00,65.00,120.00,80.00,1.00,1.00,0.00,0.00,1.00,0.00
50%,50001.50,19703.00,1.00,165.00,72.00,120.00,80.00,1.00,1.00,0.00,0.00,1.00,0.00
75%,74889.25,21327.00,2.00,170.00,82.00,140.00,90.00,2.00,1.00,0.00,0.00,1.00,1.00
max,99999.00,23713.00,2.00,250.00,200.00,16020.00,11000.00,3.00,3.00,1.00,1.00,1.00,1.00

In [13]:
df.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [14]:
duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)

Duplicate Rows : 0

In [15]:
for column in df.columns:
    print(f"{column} : {df[column].nunique()}")

id : 70000
age : 8076
gender : 2
height : 109
weight : 287
ap_hi : 153
ap_lo : 157
cholesterol : 3
gluc : 3
smoke : 2
alco : 2
active : 2
cardio : 2

In [16]:
df.sample(10, random_state=42)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
46730,66728,21770,1,156,64.00,140,80,2,1,0,0,1,1
48393,69098,21876,1,170,85.00,160,90,1,1,0,0,1,1
41416,59185,23270,1,151,90.00,130,80,1,1,0,0,1,1
34506,49288,19741,1,159,97.00,120,80,1,1,0,0,1,1
43725,62481,18395,1,164,68.00,120,80,1,1,0,0,1,0
11615,16605,20499,2,184,78.00,120,80,1,1,0,0,1,0
24656,35209,16019,1,163,60.00,120,80,1,1,0,0,1,0
22411,32015,18255,2,176,75.00,130,90,1,1,0,0,0,1
936,1307,23406,2,175,90.00,160,80,3,3,0,0,1,1
56364,80437,21021,1,145,56.00,150,80,2,1,0,0,1,0

In [17]:
df["cardio"].value_counts()

cardio
0    35021
1    34979
Name: count, dtype: int64

In [18]:
df["cardio"].value_counts(normalize=True) * 100

cardio
0   50.03
1   49.97
Name: proportion, dtype: float64

In [19]:
numerical_columns = df.select_dtypes(include=np.number).columns

print(numerical_columns)

Index(['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio'],
      dtype='str')

In [20]:
memory = df.memory_usage(deep=True).sum() / 1024**2

print(f"Dataset Memory Usage : {memory:.2f} MB")

Dataset Memory Usage : 6.94 MB

In [21]:
print("="*50)

print("DATASET SUMMARY")

print("="*50)

print(f"Rows               : {df.shape[0]}")

print(f"Columns            : {df.shape[1]}")

print(f"Missing Values     : {df.isnull().sum().sum()}")

print(f"Duplicate Rows     : {df.duplicated().sum()}")

print(f"Numerical Columns  : {len(df.select_dtypes(include=np.number).columns)}")

print("="*50)

==================================================
DATASET SUMMARY
==================================================
Rows               : 70000
Columns            : 13
Missing Values     : 0
Duplicate Rows     : 0
Numerical Columns  : 13
==================================================

In [22]:
df.to_csv("../data/processed_data/raw_dataset_copy.csv", index=False)

print("Dataset copy saved successfully.")

Dataset copy saved successfully.