In [46]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns",None)

In [47]:
df = pd.read_csv("../data/processed_data/cleaned_dataset.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [48]:
df.head()

,id,age,gender,height,weight,Systolic_BP,Diastolic_BP,cholesterol,Glucose,smoke,Alcohol,Physical_Activity,Heart_Disease,Height_m,BMI,BMI_Category,Age_Group,BP_Category,Pulse_Pressure,MAP
0,0,50.4,2,168,62.0,110,80,1,1,0,0,1,0,1.68,21.97,Normal,Senior,Stage 1,30,90.00
1,1,55.4,1,156,85.0,140,90,3,1,0,0,1,1,1.56,34.93,Obese,Senior,Stage 2,50,106.67
2,2,51.7,1,165,64.0,130,70,3,1,0,0,0,1,1.65,23.51,Normal,Senior,Stage 1,60,90.00
3,3,48.3,2,169,82.0,150,100,1,1,0,0,1,1,1.69,28.71,Overweight,Middle Age,Stage 2,50,116.67
4,4,47.9,1,156,56.0,100,60,1,1,0,0,0,0,1.56,23.01,Normal,Middle Age,Normal,40,73.33

In [49]:
print(df.columns)

Index(['id', 'age', 'gender', 'height', 'weight', 'Systolic_BP',
       'Diastolic_BP', 'cholesterol', 'Glucose', 'smoke', 'Alcohol',
       'Physical_Activity', 'Heart_Disease', 'Height_m', 'BMI', 'BMI_Category',
       'Age_Group', 'BP_Category', 'Pulse_Pressure', 'MAP'],
      dtype='str')

In [50]:
# Remove unnecessary and redundant columns

df.drop(
    columns=[
        "id",                 # Identifier
        "Height_m",           # Temporary column used only for BMI calculation
        "Age_Group",          # Derived from age
        "BMI_Category",       # Derived from BMI
        "BP_Category"         # Derived from blood pressure
    ],
    inplace=True
)

print("Remaining Columns:\n")
print(df.columns)

print("\nTotal Columns:", len(df.columns))

Remaining Columns:

Index(['age', 'gender', 'height', 'weight', 'Systolic_BP', 'Diastolic_BP',
       'cholesterol', 'Glucose', 'smoke', 'Alcohol', 'Physical_Activity',
       'Heart_Disease', 'BMI', 'Pulse_Pressure', 'MAP'],
      dtype='str')

Total Columns: 15

In [51]:
# bmi_encoder = LabelEncoder()

# df["BMI_Category"] = bmi_encoder.fit_transform(
#     df["BMI_Category"]
# )

In [52]:
# age_encoder = LabelEncoder()

# df["Age_Group"] = age_encoder.fit_transform(
#     df["Age_Group"]
# )

In [53]:
# bp_encoder = LabelEncoder()

# df["BP_Category"] = bp_encoder.fit_transform(
#     df["BP_Category"]
# )

In [54]:
df.head()

,age,gender,height,weight,Systolic_BP,Diastolic_BP,cholesterol,Glucose,smoke,Alcohol,Physical_Activity,Heart_Disease,BMI,Pulse_Pressure,MAP
0,50.4,2,168,62.0,110,80,1,1,0,0,1,0,21.97,30,90.00
1,55.4,1,156,85.0,140,90,3,1,0,0,1,1,34.93,50,106.67
2,51.7,1,165,64.0,130,70,3,1,0,0,0,1,23.51,60,90.00
3,48.3,2,169,82.0,150,100,1,1,0,0,1,1,28.71,50,116.67
4,47.9,1,156,56.0,100,60,1,1,0,0,0,0,23.01,40,73.33

In [55]:
X = df.drop("Heart_Disease",axis=1)

y = df["Heart_Disease"]

In [56]:
print("Features :",X.shape)

print("Target :",y.shape)

Features : (68036, 14)
Target : (68036,)

In [57]:
X_train,X_test,y_train,y_test = train_test_split(

    X,
    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)

In [58]:
print("Training Features :",X_train.shape)

print("Testing Features :",X_test.shape)

print("Training Labels :",y_train.shape)

print("Testing Labels :",y_test.shape)

Training Features : (54428, 14)
Testing Features : (13608, 14)
Training Labels : (54428,)
Testing Labels : (13608,)

In [59]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [60]:
print(X_train[:5])

[[ 0.05827699 -0.73593998  0.32061417 -1.01790694 -1.00274657 -1.20776723
   0.95160459  1.36593264 -0.31121087 -0.23745018  0.49426319 -1.19374049
  -0.44391584 -1.19960715]
 [-1.67148737 -0.73593998  0.32061417 -0.6488514  -0.39379474 -0.13630843
  -0.53093304 -0.39229699 -0.31121087 -0.23745018  0.49426319 -0.82235067
  -0.44391584 -0.27726053]
 [-1.00619339 -0.73593998 -0.57425785  2.00834852 -0.39379474 -0.13630843
  -0.53093304 -0.39229699 -0.31121087 -0.23745018  0.49426319  2.50777804
  -0.44391584 -0.27726053]
 [-0.7548601   1.35880646  0.57629189  0.31069302 -0.39379474 -0.13630843
  -0.53093304 -0.39229699 -0.31121087 -0.23745018  0.49426319  0.00296004
  -0.44391584 -0.27726053]
 [-0.48874251 -0.73593998 -1.72480759 -0.72266251 -0.39379474 -1.20776723
  -0.53093304 -0.39229699 -0.31121087 -0.23745018  0.49426319  0.15976907
   0.41065799 -0.89154338]]

In [61]:
X_train = pd.DataFrame(
    X_train,
    columns=X.columns
)

X_test = pd.DataFrame(
    X_test,
    columns=X.columns
)

In [62]:
X_train.head()

,age,gender,height,weight,Systolic_BP,Diastolic_BP,cholesterol,Glucose,smoke,Alcohol,Physical_Activity,BMI,Pulse_Pressure,MAP
0,0.058277,-0.735940,0.320614,-1.017907,-1.002747,-1.207767,0.951605,1.365933,-0.311211,-0.23745,0.494263,-1.193740,-0.443916,-1.199607
1,-1.671487,-0.735940,0.320614,-0.648851,-0.393795,-0.136308,-0.530933,-0.392297,-0.311211,-0.23745,0.494263,-0.822351,-0.443916,-0.277261
2,-1.006193,-0.735940,-0.574258,2.008349,-0.393795,-0.136308,-0.530933,-0.392297,-0.311211,-0.23745,0.494263,2.507778,-0.443916,-0.277261
3,-0.754860,1.358806,0.576292,0.310693,-0.393795,-0.136308,-0.530933,-0.392297,-0.311211,-0.23745,0.494263,0.002960,-0.443916,-0.277261
4,-0.488743,-0.735940,-1.724808,-0.722663,-0.393795,-1.207767,-0.530933,-0.392297,-0.311211,-0.23745,0.494263,0.159769,0.410658,-0.891543

In [63]:
feature_dataset = df.copy()

feature_dataset.to_csv(

    "../data/processed_data/feature_engineered_dataset.csv",

    index=False

)

print("Feature Engineered Dataset Saved")

Feature Engineered Dataset Saved

In [64]:
X_train.to_csv(

    "../data/train_test_data/X_train.csv",

    index=False

)

X_test.to_csv(

    "../data/train_test_data/X_test.csv",

    index=False

)

y_train.to_csv(

    "../data/train_test_data/y_train.csv",

    index=False

)

y_test.to_csv(

    "../data/train_test_data/y_test.csv",

    index=False

)

print("Train Test Dataset Saved")

Train Test Dataset Saved

In [65]:
correlation = df.corr(numeric_only=True)

target_corr = correlation["Heart_Disease"].sort_values(ascending=False)

print(target_corr)

Heart_Disease        1.000000
Systolic_BP          0.429329
MAP                  0.412180
Diastolic_BP         0.340387
Pulse_Pressure       0.330870
age                  0.239985
cholesterol          0.221179
BMI                  0.193464
weight               0.179927
Glucose              0.089029
gender               0.008328
Alcohol             -0.008199
height              -0.010639
smoke               -0.015988
Physical_Activity   -0.037690
Name: Heart_Disease, dtype: float64

In [66]:
print("="*50)

print("FINAL FEATURES")

print("="*50)

for column in X.columns:

    print(column)

==================================================
FINAL FEATURES
==================================================
age
gender
height
weight
Systolic_BP
Diastolic_BP
cholesterol
Glucose
smoke
Alcohol
Physical_Activity
BMI
Pulse_Pressure
MAP

In [67]:
print("="*60)

print("FEATURE ENGINEERING COMPLETED")

print("="*60)

print("Training Samples :",len(X_train))

print("Testing Samples :",len(X_test))

print("Total Features :",X_train.shape[1])

print("="*60)

============================================================
FEATURE ENGINEERING COMPLETED
============================================================
Training Samples : 54428
Testing Samples : 13608
Total Features : 14
============================================================